import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import ProtectedPage from "@/app/ProtectedPage";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Attendance Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ProtectedPage>
          {children}
      </ProtectedPage>
      </body>
    </html>
  );
}
